camera_pos: "rtsp://admin:Cogn!@2023@192.168.1.48:554/Streaming/channels/102/"              #For M series (0,2,4,6), for s series url.
cam_id: 1 #For M series (0-3) For s series (0-5)

# ex: M series : cam_pos=2 ,cam_id=1  map cam_pos(0,2,4,6) with  cam_id (0-3)
# For both S andM-series flip=0 irrespective of the camera(all cams)

# # ---------- M-series  ----------
# # ---------- BACKGROUND POSITIONS ----------
# background_p0:
#   window_place_x: 0
#   window_place_y: 0
#   window_size_x: 1024
#   window_size_y: 380
#   flip: 0
#   rotate: 0

# background_p1:
#   window_place_x: 0
#   window_place_y: 445
#   window_size_x: 430
#   window_size_y: 380
#   flip: 0
#   rotate: 1

# background_p2:
#   window_place_x: 650
#   window_place_y: 445
#   window_size_x: 430
#   window_size_y: 380
#   flip: 0
#   rotate: 2

# background_p3:
#   window_place_x: 0
#   window_place_y: 880
#   window_size_x: 1024
#   window_size_y: 380
#   flip: 0
#   rotate: 0


# # ---------- ZONE COORDINATES ----------
# p0_zone_coords:  # Front
#   red:
#     - [640, 480]
#     - [576, 360]
#     - [64, 360]
#     - [0, 480]


#   orange:
#     - [576, 360]
#     - [512, 288]
#     - [128, 288]
#     - [64, 360]
#   blue:
#     - [512, 288]
#     - [448, 240]
#     - [192, 240]
#     - [128, 288]
#   line_thickness: 2
#   num_zones: 3

# p1_zone_coords:   # Left 
#   red:
#     - [640, 480]
#     - [576, 360]
#     - [64, 360]
#     - [0, 480]



#   orange:
#     - [576, 360]
#     - [512, 288]
#     - [128, 288]
#     - [64, 360]
#   blue:
#     - [512, 288]
#     - [448, 240]
#     - [192, 240]
#     - [128, 288]
#   line_thickness: 2
#   num_zones: 3

# p2_zone_coords:  # Right
#   red:
#     - [640, 480]
#     - [576, 360]
#     - [64, 360]
#     - [0, 480]

#   orange:
#     - [576, 360]
#     - [512, 288]
#     - [128, 288]
#     - [64, 360]
#   blue:
#     - [512, 288]
#     - [448, 240]
#     - [192, 240]
#     - [128, 288]
#   line_thickness: 2
#   num_zones: 3

# p3_zone_coords:  # Back
#   red:
#     - [640, 480]
#     - [576, 360]
#     - [64, 360]
#     - [0, 480]
#   orange:
#     - [576, 360]
#     - [512, 288]
#     - [128, 288]
#     - [64, 360]
#   blue:
#     - [512, 288]
#     - [448, 240]
#     - [192, 240]
#     - [128, 288]
#   line_thickness: 2
#   num_zones: 3


# ======================== S SERIES CAMERAS (6) ========================

# --- Backgrounds for 6 cams ---
background_p0:  # S Cam 1
  window_place_x: 0
  window_place_y: 0
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0

background_p1:  # S Cam 2
  window_place_x: 640
  window_place_y: 0
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0

background_p2:  # S Cam 3
  window_place_x: 1480
  window_place_y: 0
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0

background_p3:  # S Cam 4
  window_place_x: 0
  window_place_y: 552
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0

background_p4:  # S Cam 5
  window_place_x: 640
  window_place_y: 552
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0

background_p5:  # S Cam 6
  window_place_x: 1480
  window_place_y: 552
  window_size_x: 640
  window_size_y: 490
  flip: 0
  rotate: 0


# --- S series zones (as you provided) ---
p0_zone_coords:  # S Cam 1
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [640, 480]  # red_left_bottom
    - [630, 0]
    - [300, 0]
    - [300, 300]
    - [500, 480]


  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1


p1_zone_coords:  # S Cam 2
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [104, 107]  # red_left_bottom
    - [103, 457]
    - [620, 439]

  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1


p2_zone_coords:  # S Cam 3
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [640, 480]  # red_left_bottom
    - [600, 0]
    - [0, 0]
    - [0, 480]

  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1


p3_zone_coords:  # S Cam 4
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [640, 480]  # red_left_bottom
    - [600, 0]
    - [0, 0]
    - [0, 480]
  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1


p4_zone_coords:  # S Cam 5
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [640, 480]  # red_left_bottom
    - [600, 0]
    - [0, 0]
    - [0, 480]

  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1


p5_zone_coords:  # S Cam 6
  red:    #left (640,480b/0t) right(0,0t/480b)
    - [640, 480]  # red_left_bottom
    - [600, 0]
    - [0, 0]
    - [0, 480]

  orange: []
  blue: []
  line_thickness: 2
  num_zones: 1

